### ISSUE TITLE
Polling vs PubSub

### ISSUE THREAD

**Issue by jpallen** [baoshan/fairy#6]
Have you considered using the [Redis pub/sub](http://redis.io/topics/pubsub) features instead of polling every 5ms? It would help with CPU load quite a bit! The implementation I have in mind is to get rid of the following line at the end of `_poll`:

```
setTimeout @_poll, @polling_interval
```

The polling could then be reactivated by subscribing to a channel like `FAIRY:NEW_JOBS:<queue-name>` which would be published to whenever `queue.enqueue()` is called. This way the whole thing would sit idle until there was actually something to do. I believe that the current implementation would then clean out the whole `SOURCE` queue without needing to poll again, but I could be wrong about this.

Is there a reason you chose polling? Sometimes things that seem like a good idea from the outside are actually avoided for good reasons, so I apologise if that's the case. If you don't have any objections I will likely spend some time converting fairy over to pub/sub rather than polling when I get the time.

(I'm working with @henryoswald on a project that uses fairy, hence the interest from us.)

**Comment by baoshan** [comment]
Solved.
